// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoundMate.Infrastructure.Persistence;

#nullable disable

namespace SoundMate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SoundMateDbContext))]
    [Migration("20260826144510_AcademySoftDelete")]
    partial class AcademySoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoundMate.Domain.Academies.Academy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAtUtc")
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Academies", (string)null);
                });

            modelBuilder.Entity("SoundMate.Domain.Disciplines.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Disciplines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = 1,
                            IsActive = true,
                            Name = "Piano"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = 1,
                            IsActive = true,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = 1,
                            IsActive = true,
                            Name = "Organ"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = 1,
                            IsActive = true,
                            Name = "Accordion"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Category = 2,
                            IsActive = true,
                            Name = "Classical guitar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Category = 2,
                            IsActive = true,
                            Name = "Acoustic guitar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Category = 2,
                            IsActive = true,
                            Name = "Electric guitar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Category = 2,
                            IsActive = true,
                            Name = "Flamenco guitar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Category = 2,
                            IsActive = true,
                            Name = "Electric bass"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Category = 2,
                            IsActive = true,
                            Name = "Ukulele"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Category = 2,
                            IsActive = true,
                            Name = "Banjo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Category = 2,
                            IsActive = true,
                            Name = "Mandolin"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Category = 2,
                            IsActive = true,
                            Name = "Harp"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000a"),
                            Category = 2,
                            IsActive = true,
                            Name = "Bandurria"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000b"),
                            Category = 2,
                            IsActive = true,
                            Name = "Lute"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Category = 3,
                            IsActive = true,
                            Name = "Violin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Category = 3,
                            IsActive = true,
                            Name = "Viola"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Category = 3,
                            IsActive = true,
                            Name = "Cello"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Category = 3,
                            IsActive = true,
                            Name = "Double bass"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Category = 4,
                            IsActive = true,
                            Name = "Flute"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Category = 4,
                            IsActive = true,
                            Name = "Recorder"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Category = 4,
                            IsActive = true,
                            Name = "Clarinet"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Category = 4,
                            IsActive = true,
                            Name = "Saxophone"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Category = 4,
                            IsActive = true,
                            Name = "Oboe"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            Category = 4,
                            IsActive = true,
                            Name = "Bassoon"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Category = 5,
                            IsActive = true,
                            Name = "Trumpet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Category = 5,
                            IsActive = true,
                            Name = "Trombone"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Category = 5,
                            IsActive = true,
                            Name = "French horn"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Category = 5,
                            IsActive = true,
                            Name = "Tuba"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Category = 5,
                            IsActive = true,
                            Name = "Euphonium"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Category = 5,
                            IsActive = true,
                            Name = "Cornet"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Category = 5,
                            IsActive = true,
                            Name = "Flugelhorn"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Category = 6,
                            IsActive = true,
                            Name = "Drum kit"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Category = 6,
                            IsActive = true,
                            Name = "Snare drum"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Category = 6,
                            IsActive = true,
                            Name = "Cajón"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Category = 6,
                            IsActive = true,
                            Name = "Congas"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            Category = 6,
                            IsActive = true,
                            Name = "Bongos"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            Category = 6,
                            IsActive = true,
                            Name = "Djembe"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000007"),
                            Category = 6,
                            IsActive = true,
                            Name = "Timpani"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000008"),
                            Category = 6,
                            IsActive = true,
                            Name = "Mallet percussion"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Category = 7,
                            IsActive = true,
                            Name = "Singing"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Category = 7,
                            IsActive = true,
                            Name = "Classical voice"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Category = 8,
                            IsActive = true,
                            Name = "Music theory"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            Category = 8,
                            IsActive = true,
                            Name = "Harmony"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            Category = 8,
                            IsActive = true,
                            Name = "Composition"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            Category = 8,
                            IsActive = true,
                            Name = "Music analysis"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000005"),
                            Category = 8,
                            IsActive = true,
                            Name = "Music history"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000006"),
                            Category = 8,
                            IsActive = true,
                            Name = "Improvisation"
                        });
                });

            modelBuilder.Entity("SoundMate.Domain.Genres.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Opera"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Baroque"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Contemporary classical"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Name = "Swing"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Name = "Bossa nova"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000000a"),
                            IsActive = true,
                            Name = "Hard rock"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000000b"),
                            IsActive = true,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000000c"),
                            IsActive = true,
                            Name = "Punk"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000000d"),
                            IsActive = true,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000000e"),
                            IsActive = true,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000000f"),
                            IsActive = true,
                            Name = "Funk"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000011"),
                            IsActive = true,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000012"),
                            IsActive = true,
                            Name = "Hip hop"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000013"),
                            IsActive = true,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000014"),
                            IsActive = true,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000015"),
                            IsActive = true,
                            Name = "Ska"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000016"),
                            IsActive = true,
                            Name = "Reggaeton"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000017"),
                            IsActive = true,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000018"),
                            IsActive = true,
                            Name = "House"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000019"),
                            IsActive = true,
                            Name = "Techno"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000001a"),
                            IsActive = true,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000001b"),
                            IsActive = true,
                            Name = "Country"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000001c"),
                            IsActive = true,
                            Name = "Flamenco"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000001d"),
                            IsActive = true,
                            Name = "Latin"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000001e"),
                            IsActive = true,
                            Name = "Salsa"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-00000000001f"),
                            IsActive = true,
                            Name = "Tango"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000020"),
                            IsActive = true,
                            Name = "Gospel"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000021"),
                            IsActive = true,
                            Name = "Film music"
                        });
                });

            modelBuilder.Entity("SoundMate.Domain.Memberships.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId");

                    b.HasIndex("UserId", "AcademyId", "Role")
                        .IsUnique();

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("SoundMate.Domain.Teaching.TeacherDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("TeacherDisciplines", (string)null);
                });

            modelBuilder.Entity("SoundMate.Domain.Teaching.TeacherGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("UserId", "GenreId")
                        .IsUnique();

                    b.ToTable("TeacherGenres", (string)null);
                });

            modelBuilder.Entity("SoundMate.Domain.Teaching.TeacherReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId", "AcademyId");

                    b.HasIndex("ReviewerUserId", "TeacherUserId", "AcademyId")
                        .IsUnique();

                    b.ToTable("TeacherReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeacherReviews_Stars", "\"Stars\" >= 1 AND \"Stars\" <= 5");
                        });
                });

            modelBuilder.Entity("SoundMate.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAtUtc")
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SoundMate.Domain.Users.UserDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("UserDisciplines", (string)null);
                });

            modelBuilder.Entity("SoundMate.Domain.Users.UserEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEducations", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserEducations_Years", "\"StartYear\" IS NULL OR \"EndYear\" IS NULL OR \"EndYear\" >= \"StartYear\"");
                        });
                });

            modelBuilder.Entity("SoundMate.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
